### ISSUE TITLE
Second Widget of same type does not work with drop down button

### ISSUE THREAD

**Issue by anamite** [Akascape/CTkScrollableDropdown#1]
![image](https://github.com/Akascape/CTkScrollableDropdown/assets/77412636/3edf2023-6bd9-4bda-812f-855673237847)

Adding a second widget of same type (ie; Optionmenu or ComboBox) apparently affects the dropdown button.(the first widget works fine, but the second onwards, it just shows the titel)

**Comment by Akascape** [comment]
@tripnip Thanks for figuring this out, I was actually not aware of it.
But I fixed this issue, and also added autocomplete feature.
Now you don't have to add commands for ctkcombobox/optionmenu. The values will be updated after selecting.

**Comment by anamite** [comment]
As a suggetion, maybe in the future updates, it would be great to add arguments to give specific color to the selector, change the selector-border radius, and also maybe to use customised font and font-size inside the dropdown box.
Anyways, i am glad that i was able to get to use your code for my project :)

**Comment by Akascape** [comment]
@tripnip All parameters for ctkbutton can be passed as the option values like font, border_width, hover_color etc.
See the argument table, everything is customizable.

**Comment by anamite** [comment]
@Akascape 
Ahh i get it now, missed that part.
Thanks 👍 :)
