### ISSUE TITLE
Collapse dropdown when clicking outside of it

### ISSUE THREAD

**Issue by DimaTepliakov** [Akascape/CTkScrollableDropdown#13]
Hi there,

I'd like to express my appreciation for this innovative solution.

I've encountered an issue where, when the dropdown is open, clicking outside of it doesn't collapse or withdraw it. This results in the ability to open multiple scrollable dropdowns simultaneously, potentially hiding each other. I've created a video to demonstrate the problem:

https://github.com/Akascape/CTkScrollableDropdown/assets/69217590/380817b7-069d-4ec4-9efb-e6f1a4734ffa

Here's a snippet of the code:

    def create_widgets(self):

        for row, parameter_key in enumerate(self.parameters):
            parameter_name = parameter_key.name
            parameter_title = parameter_name.replace("_", " ").title() + ":"
            parameter_values = self.create_list_of_string_values(parameter_name)
            parameter_decimal_point = self.get_algo_param_value_by_type(parameter_name, 'DECIMAL_POINT')

            param_label = ctk.CTkLabel(self.parameters_frame, font=roboto(15), text=parameter_title)
            param_option_menu = ctk.CTkOptionMenu(self.parameters_frame, font=roboto(15))
            CTkScrollableDropdown(param_option_menu, font=roboto(15), values=parameter_values, command=lambda e, param_key=parameter_key: self.set_parameter(param_key, e), double_click=True)

            param_option_menu.set(np.round(self.audio_device_client.get_parameter(parameter_key), parameter_decimal_point))
            self.parameters_option_menus[parameter_key] = param_option_menu

            # Create a callback function with the correct parameter_key
            callback_func = self.create_option_menu_callback(parameter_key)
            param_option_menu.configure(command=callback_func)

            param_label      .grid(row=row, column=0, padx=20, pady=(20 if row == 0 else 0, 8), sticky="w")
            param_option_menu.grid(row=row, column=1, padx=20, pady=(20 if row == 0 else 0, 8), sticky="w")
        
        self.algo_params_status_bar_label = ctk.CTkLabel(self, text=f'', bg_color="transparent", 
                                                      fg_color=grey_fg_color, anchor="center", corner_radius=3)
        self.algo_params_status_bar_label.grid(row=1, column=0, columnspan=3, pady=60, sticky="nsew")
        
In the video, you'll notice that clicking three times consecutively on the left mouse button or once on the right button outside the dropdown closes it. I'm seeking guidance on how to modify it so that a single right-click outside the dropdown closes it, aligning with the expected behavior of a dropdown.

Thank you for any assistance or insights you can provide.

**Comment by Akascape** [comment]
Hi @DimaTepliakov , thanks for your feedback, I fixed the mouse click issue. Now a single click outside the dropdown closes it, update to the latest version.

**Comment by DimaTepliakov** [comment]
Hi @Akascape, thanks for the update now it works perfectly.

One other little thing I noticed is that I think it's a line
140 in CTkScrollableDropdownFrame's file
And on line 138 in the CTkScrollableDropdown file
it should be self.i:
image=self.image_values[**self.i**] if self.image_values is not None else None,

instead of just i:
image=self.image_values[**i**] if self.image_values is not None else None,
