### ISSUE TITLE
When use command option, the combobox don't load the option chosed

### ISSUE THREAD

**Issue by Atzuke** [Akascape/CTkScrollableDropdown#15]
Hi

I recently download the library, its very usefull... but when i use the option "command" to load the values ot other ComboBox, the actual combobox cant show the option that the user select.

**Comment by Phayzex** [comment]
> Hi
> 
> I recently download the library, its very usefull... but when i use the option "command" to load the values ot other ComboBox, the actual combobox cant show the option that the user select.

I couldn't get the command to function consistently so I just made a bind event that works just as fine.

Here is a simple example:

```
self.dropdown.bind("<<Selected>>", self.schedule_update)

def schedule_update(self, event):
    self.after(300, self.update_callback)
```
