### ISSUE TITLE
Enhancement Request - Addition of "dropdown_hover_color" Parameter in CTkScrollableDropdown Method

### ISSUE THREAD

**Issue by EduardoWS** [Akascape/CTkScrollableDropdown#19]
I am reaching out to propose an enhancement for the CTkScrollableDropdown method in your GitHub project. The suggested modification involves the addition of a new parameter called "dropdown_hover_color," designed to offer users the flexibility to customize the hover color of buttons within the dropdown.

Best regards,
Edu

**Comment by Akascape** [comment]
@EduardoWS Did you try passing just `hover_color`?

**Comment by EduardoWS** [comment]
> @EduardoWS Did you try passing just `hover_color`?

Ah, I had just tried the "dropdown_hover_color" that is in the combobox. 
It worked here, thanks!

One last thing I wanted to ask, the scroll of this combobox is not working with the MouseWhell, is it on purpose or is it an error? It only works when I click on the bar and drag down or up

**Comment by Akascape** [comment]
@EduardoWS If you are on linux then you may face the mousewheel issue. It's fault in ctkscrollable frame which is used for making this dropdown.

See issue: https://github.com/TomSchimansky/CustomTkinter/issues/1356

**Comment by EduardoWS** [comment]
> @EduardoWS If you are on linux then you may face the mousewheel issue. It's fault in ctkscrollable frame which is used for making this dropdown.
> 
> See issue: [TomSchimansky/CustomTkinter#1356](https://github.com/TomSchimansky/CustomTkinter/issues/1356)

I am on Windows 11

**Comment by Akascape** [comment]
@EduardoWS Then there shouldn't be any issue in this dropdown. Did you try the basic examples? Also let me know if mousewheel in  ctkscrollableframe is working or not.

I will check this later...

**Comment by EduardoWS** [comment]
@Akascape 

I already know what it is. I modified the CTkScrollableFrame like this:

```python
class ModifiedCTkScrollableFrame(CTkScrollableFrame):
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)

        # Remover o binding global do mouse wheel
        self.unbind_all("<MouseWheel>")

        # Adicionar o novo binding específico para o scroll_frame
        self._parent_canvas.bind_all("<MouseWheel>", self._mouse_wheel_scroll_frame, add="+")

    def _mouse_wheel_scroll_frame(self, event):
        # Verifique se o widget ainda existe
        if not self._parent_canvas.winfo_exists():
            return
        
        if sys.platform.startswith("win"):
            if self._shift_pressed:
                if self._parent_canvas.xview() != (0.0, 1.0):
                    self._parent_canvas.xview("scroll", -int(event.delta / 6), "units")
            else:
                if self._parent_canvas.yview() != (0.0, 1.0):
                    self._parent_canvas.yview("scroll", -int(event.delta / 6), "units")
        elif sys.platform == "darwin":
            if self._shift_pressed:
                if self._parent_canvas.xview() != (0.0, 1.0):
                    self._parent_canvas.xview("scroll", -event.delta, "units")
            else:
                if self._parent_canvas.yview() != (0.0, 1.0):
                    self._parent_canvas.yview("scroll", -event.delta, "units")
        else:
            if self._shift_pressed:
                if self._parent_canvas.xview() != (0.0, 1.0):
                    self._parent_canvas.xview("scroll", -event.delta, "units")
            else:
                if self._parent_canvas.yview() != (0.0, 1.0):
                    self._parent_canvas.yview("scroll", -event.delta, "units")
 ```
 
I did this so I could make a focus/lose focus system. I have a screen with a frame of type CTkScrollableFrame and inside it has CTkTextbox (with scrollbars). In other words, there were two scrollbars on the same screen. When using the MouseWhell the two moved, this was bad. Therefore, I made this change to move just one based on mouse focus, as per the code below:

```python
def _enter_textbox(event, scroll_frame):
    altura = textbox_frame.cget('height')
    if altura == 400:
    scroll_frame.unbind_all("<MouseWheel>")


def _leave_textbox(event, scroll_frame):
     scroll_frame.bind_all("<MouseWheel>", scroll_frame._mouse_wheel_scroll_frame, add="+")
     event.widget.unbind("<MouseWheel>")
        
textbox_frame.bind("<Enter>", lambda event: _enter_textbox(event, scroll_frame))
textbox_frame.bind("<Leave>", lambda event: _leave_textbox(event, scroll_frame))
```

With that, I realized that the other CTkScrollableFrames in my program no longer worked with MouseWhell, and so I changed them all to use this modified class instead of the original. Since your script uses the original class, it's not working for me. I changed the code in your file and added this modification. However, even with the mouse outside the CTkScrollableFrame, it continues to scroll down when I have the mouse in the dropdown
