### ISSUE TITLE
Top window Bar (in dark mode) changes color when dropdown in use

### ISSUE THREAD

**Issue by anamite** [Akascape/CTkScrollableDropdown#2]
![image](https://github.com/Akascape/CTkScrollableDropdown/assets/77412636/d53e4a90-caf9-4fb5-8b6c-7b5324fcd4c1)
![image](https://github.com/Akascape/CTkScrollableDropdown/assets/77412636/1b950c04-2a92-4bc2-9881-dd5eb6d0da33)
I just noticed that as i click to open the drop down the tob bar of the window changes color to ~grey (noticed in darkmode of customtkinter)

**Comment by Akascape** [comment]
@tripnip 
This is a issue with custoktkinter. When a new window is focused, the previous window header changes the color. So I will recommend you to change the color of header using this method permanently.

```python
import customtkinter
from ctypes import windll, byref, sizeof, c_int

root = customtkinter.CTk()

HWND = windll.user32.GetParent(root.winfo_id()) # the window we want to change

# These attributes are for windows 11 only 
DWMWA_CAPTION_COLOR = 35 # 35 is for title bar color

# color should be in this order: 0x00bbggrr
COLOR_1 = 0x00000000

windll.dwmapi.DwmSetWindowAttribute(HWND, DWMWA_CAPTION_COLOR, byref(c_int(COLOR_1)), sizeof(c_int))

root.mainloop()
```

But still, I will try to change the focus issue.

**Comment by Akascape** [comment]
@tripnip It's fixed. Now the header color doesn't change in windows.

**Comment by anamite** [comment]
Thanks a lot :)
