### ISSUE TITLE
When I use it with CTk Toplevel it doesn't work

### ISSUE THREAD

**Issue by jorgarmolina** [Akascape/CTkScrollableDropdown#20]
I have made a small program and I have used CTk SCrollable Dropdown, if I use it on the main screen (ctk.CTk) the control works fine but if I use it with (ctk.CTkToplevel) it does not work well.

**Comment by BMP-TUD** [comment]
Also same issue here, in main window perfect, in toplevel not working what at all.

Greetings, 
Bartosz

**Comment by Akascape** [comment]
@BMP-TUD Please send an example, I am not facing any issue in windows

**Comment by manyinc** [comment]
I also have this problem, see the screenshot below. Execution of a sample program
attached to CTkScrollableDropdown example.py

![Przechwytywanie](https://github.com/Akascape/CTkScrollableDropdown/assets/132141585/af69ba11-b332-4ef3-9abb-38a79cc62a23)

**Comment by Akascape** [comment]
@manyinc Which version of customtkinter you are using?

**Comment by BMP-TUD** [comment]
Sorry for not sending an example, the app is quite large, but @manyinc was able to reproduce it. And I am using version 5.2.1 of customtkinter

**Comment by Akascape** [comment]
Please update to the latest version of ctk and also download the latest CtkScrollableDropdown.
Let me know if its still showing that error

**Comment by BMP-TUD** [comment]
I updated both ctk and your code and now it shows a different error:

```
bad window path name ".!ctkscrollabledropdown2"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\...\Anaconda3\envs\database\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\...\Anaconda3\envs\database\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\Users\...\Anaconda3\envs\database\Lib\site-packages\customtkinter\windows\ctk_toplevel.py", line 295, in _revert_withdraw_after_windows_set_titlebar_color
    self.state(self._state_before_windows_set_titlebar_color)  # other states
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\Anaconda3\envs\database\Lib\tkinter\__init__.py", line 2290, in wm_state
    return self.tk.call('wm', 'state', self._w, newstate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad window path name ".!ctkscrollabledropdown2"
```

**Comment by Akascape** [comment]
@BMP-TU your python version? Maybe it's due to python version difference.

**Comment by BMP-TUD** [comment]
My python version is 3.12.1, this indeed could be a problem, which version have you been using?

**Comment by Akascape** [comment]
@BMP-TU I am using 3.10, let me install the new version.

**Comment by Akascape** [comment]
@BMP-TUD NO issues in the latest version. It's probably because of deleted widgets where dropdown is not removed.

**Comment by manyinc** [comment]
@Akascape Thank you, updating customtkinter 4.5.1 -> 5.2.2 helped.

**Comment by manyinc** [comment]
@Akascape The option does not work "hover_color" please can you check ?

And hiding the dropdown menu after clicking the arrow does not work.

CTkScrollableDropdown(combobox, values=values, justify="left", hover_color="#10888c", button_color="transparent")

![image](https://github.com/Akascape/CTkScrollableDropdown/assets/132141585/487dee61-bea1-4dc0-9a11-22ffc5579a73)

**Comment by monolith04** [comment]
> @Akascape The option does not work "hover_color" please can you check ?
> 
> And hiding the dropdown menu after clicking the arrow does not work.
> 
> CTkScrollableDropdown(combobox, values=values, justify="left", hover_color="#10888c", button_color="transparent")
> 
> ![image](https://private-user-images.githubusercontent.com/132141585/295749884-487dee61-bea1-4dc0-9a11-22ffc5579a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDEzNTQsIm5iZiI6MTcxMzgwMTA1NCwicGF0aCI6Ii8xMzIxNDE1ODUvMjk1NzQ5ODg0LTQ4N2RlZTYxLWJlYTEtNGRjMC05YTExLTIyZmZjNTU3OWE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNTUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODU5MzU2M2NiYTJjMWM4MTkxM2JkNWNhOWEyZDdiZmFlY2ZmODZiZDJmMDI1MzEzNGU0OTljNDk3NzA3NTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jW33_jiNWyncpqJAOYB9TTNXHaUnVMBJn-Q1KorcFw8)

Same problem with "hover_color" attribute. 
@Akascape

**Comment by Akascape** [comment]
Try the new version, I have fixed this issue.
