### ISSUE TITLE
Issue with Autocomplete

### ISSUE THREAD

**Issue by xmarco81** [Akascape/CTkScrollableDropdown#23]
Hi, first of all thanks for this code that helped me a lot with my project!

I have an issue with the lambda function for the autocomplete.
in detail when I start typing the name of a country (e.g. It - for Italy) the script works but when I click on the button Italy ne value in the page becomes **I**Itali**t**

Is there a way to cancel what has been typed from users so that the name of the country match with the country clicked?
here below the part of code that is not working properly.

`self.entry = ctk.CTkEntry(self.frame1, border_color='#fe701a',width=200)`
`self.entry.grid(column=2, row=3, sticky='W', padx=4, pady=2)`
`self.Country = CTkScrollableDropdown(self.entry, border_color='#fe701a',values=RANK.tolist(),
                                            command=lambda e: self.entry.insert(1, e), autocomplete=True) # Using autocomplete`

thanks a lot!

**Comment by Akascape** [comment]
@xmarco81 will fix this, don't worry:)

**Comment by Akascape** [comment]
@xmarco81 Check this:
```python
def insert_method(e):
    entry.delete(0, 'end')
    entry.insert(0, e)

CTkScrollableDropdown(entry, values=values, command=lambda e: insert_method(e),
                      autocomplete=True) # Using autocomplete
``
