### ISSUE TITLE
hover color not changing

### ISSUE THREAD

**Issue by BhagyaJyoti22006** [Akascape/CTkScrollableDropdown#25]
'''
self.main_list = customtkinter.CTkOptionMenu(self.main_frame)
self.main_list.configure(width=170)
self.main_list.place(x=80,y=96)
self.main_dropdown = CTkScrollableDropdown.CTkScrollableDropdown(self.main_list, hover_color="#FF00FF")
'''
hover_color is not changing hover color of individual list items.

**Comment by Akascape** [comment]
@BhagyaJyoti22006 Not facing this issue, please provide more details
![Screenshot 2024-01-09 150037](https://github.com/Akascape/CTkScrollableDropdown/assets/89206401/05945e66-891c-4053-9611-4f0f05a43a96)
Make sure to use the latest version

**Comment by lgander** [comment]
Just want to add that I'm using customtkinter with a custom theme and for me this doesn't work neither. 
Instead of the hover_color property  of the dropdown, the hover_color of the CTkButton in the custom theme is the one that is being showed.
