### ISSUE TITLE
corner/frame_corner_radius argument

### ISSUE THREAD

**Issue by nexperion** [Akascape/CTkScrollableDropdown#38]
The "corner" argument described in the documentation does not exist, the correct name seems to be frame_corner_radius.

This parameter seems not to have any effect in CTkToplevel.

**Comment by Akascape** [comment]
@nexperion Are you on a linux based OS? Corner radius doesn't work there due to system limitation with tkinter. See why [here](https://stackoverflow.com/questions/75594687/how-to-apply-transparent-background-in-tkinter-window-of-linux-not-alpha)

**Comment by nexperion** [comment]
Can confirm that this happened on Linux. Thank you @Akascape

**Comment by nexperion** [comment]
I suggest to change the documentation regardless ... it says "corner" instead of frame_corner_radius.
![Screenshot from 2024-05-26 20-01-58](https://github.com/Akascape/CTkScrollableDropdown/assets/170871358/795aac8b-56ed-4843-ad5d-a61ffe988de5)
