### ISSUE TITLE
Hover_color not working in CTkComboBox

### ISSUE THREAD

**Issue by Demsli** [Akascape/CTkScrollableDropdown#42]
Tried setting hover_color to both OptionMenu and ComboBox. While the first one worked, the second one - did not. The hover color for ComboBox remains default. Though it should have been changed to Ash Grey (#CBD4C2). Here is the sample code:

import customtkinter as ctk
from CTkScrollableDropdown import *
class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.geometry('300x300')
        self.column_button = ctk.CTkComboBox(self, justify='center', width=200, text_color=('#50514F', '#FFFCFF'),
                                             button_color=("#C3B299","#247BA0"), dropdown_hover_color='#CBD4C2', button_hover_color='#CBD4C2')
        self.column_button_prettified = CTkScrollableDropdown(attach=self.column_button, values=['A', 'B', 'C', 'D', 'E', 'F'], justify='center', width=200,
                                                              text_color=('#50514F', '#FFFCFF'), fg_color=('#FFFCFF', '#50514F'), button_color=('#FFFCFF', '#50514F'), hover_color='#CBD4C2')
        self.column_button.pack(pady=16)

app = App()
app.mainloop()

OS: Windows 10
Python ver: 3.11.9
Customtkinter: 5.2.2

**Comment by Akascape** [comment]
@Demsli Try the new version
