### ISSUE TITLE
Not working properly on CTkTopLevelWindow

### ISSUE THREAD

**Issue by BudenzaubR** [Akascape/CTkScrollableDropdown#43]
Hi @Akascape ,

I am already using your CTkScrollableDropdown in a usual frame inside the main CTk() which is working fine, but when I open a CTkTopLevelWindow to select something the widget does not work properly. No matter if I attach it to a CTkComboBox or a CTkOptionMenu, both have the same issue in that you cannot select any of the values and cant even use the scrollbar. Any click on the widget simply closes it.

    from typing import List
    import customtkinter as ctk
    from src.CTkScrollableDropdown import CTkScrollableDropdown

    class SelectSomeoneWindow(ctk.CTkToplevel):
      def __init__(self, master):
          super().__init__()
  
          # Instance Variables
          self.master = master
  
          # Configure TopLevelWindow
          self.geometry("600x200")
          self.resizable(False, False)
          self.title("Select Someone")
          self.grid_columnconfigure((0, 1), weight=1)
          self.grab_set()
  
          # Add Widgets
          self.comboboxLabel = ctk.CTkLabel(self, text="Select Someone:", anchor="w")
          self.comboboxLabel.grid(row=0, column=0, padx=20, pady=20, sticky="ew")
  
          self.comboBox = ctk.CTkComboBox(self, width=300, values=[])
          self.comboBox.grid(row=0, column=1, padx=20, pady=20)
  
          self.allValues: List[str] = ["Person 1", "Person 2", "Person 3", "Person 4", "Person 5"]
  
          self.scrollableGuestMemberDropDown = CTkScrollableDropdown(
              self.comboBox,
              values=self.allValues,
              justify="left",
              hover_color="#94C120",
          )
  
          self.startServiceButton = ctk.CTkButton(
              self,
              text="OK",
              width=300,
              height=100,
              anchor="",
              compound="left",
              command=self.doSomething,
          )
          self.startServiceButton.grid(row=1, column=0, padx=20, pady=20)
  
          self.startServiceButton = ctk.CTkButton(
              self,
              text="Cancel",
              width=300,
              height=100,
              anchor="",
              compound="left",
              command=self.destroy,
          )
          self.startServiceButton.grid(row=1, column=1, padx=20, pady=20)
  
      def doSomething(self):
          try:
              print("Do something")
          except Exception as err:
              print("Something went wrong")
  
  
      app = ctk.CTk()
      app.title("Main")
      select = SelectSomeoneWindow(app)
      app.mainloop()

Hope you can figure it out.
Thanks in advance!

**Comment by Akascape** [comment]
@BudenzaubR Try the new version
