### ISSUE TITLE
Button is transparent

### ISSUE THREAD

**Issue by AinRyzen** [Akascape/CTkScrollableDropdown#45]
![image](https://github.com/Akascape/CTkScrollableDropdown/assets/132378981/664a0c13-a2ca-4977-b990-4355c4195373)

**Comment by AinRyzen** [comment]
Please fix

**Comment by Akascape** [comment]
@AinRyzen Please provide an example, I tested and not facing any issue. Make sure you pass `button_color="transparent".`

**Comment by AinRyzen** [comment]
This fixed it, button_color="transparent". So thank you
