### ISSUE TITLE
CTkScrollableDropdown opening multiple CTkTopLevel on app start

### ISSUE THREAD

**Issue by teijiIshida** [Akascape/CTkScrollableDropdown#47]
For some reason, whenever I start my app, it opens multiple CTkTopLevel (depending on how many CTkScrollableDropdown I have created) before the app start. For example, I have 11 CTkOptionMenu which have 11 CTkScrollableDropdown. When I start my app, I notice it blinks 11 times with CTkTopLevel in the title before my app starts. As soon as I remove those 11 CTkScrollableDropdown, my app starts immediately without blinking 11 times.

Another issue:
I tried CTkScrollableDropdownFrame, which doesn't have the problem above. But I can't set the height correctly. I have this CTkOptionMenu which only has 3 values (Light, Dark, System). I tried setting height to 90, which should fit the 3 buttons. But the CTkScrollableDropdownFrame refuses to set it. The height was long like more than double of that (could probably fit 6 or 7 values). It was still the same regardless if resize=True or False.

**Comment by Akascape** [comment]
@teijiIshida Both issues fixed, try the new version and let me know :)

**Comment by teijiIshida** [comment]
Thank you. Yes, both bugs are fixed.
