### ISSUE TITLE
Publish on PyPi

### ISSUE THREAD

**Issue by CallMePixelMan** [Akascape/CTkScrollableDropdown#7]
Hello! [Exactly like last time](https://github.com/Akascape/CTkListbox/issues/1#event-9743275955), I would love to be able to install your package with pip instead of downloading the sources.

I find myself depending greatly from your widgets, is it possible to publish them all on PyPi?

Thanks a lot

**Comment by Akascape** [comment]
Not for now, it is still in experimental stage...
