### ISSUE TITLE
CTkScrollableDropdown not working when grab_set() is active

### ISSUE THREAD

**Issue by hassan-anari** [Akascape/CTkScrollableDropdown#8]
Hi, I used CTkScrollableDropdown inside a top level and I ran into a problem. The problem was that the option menu was opened, but it was not possible to select there options. Until I realized that when I comment the grab_set() method, it works correctly... we can use attributes("-topmost", True) instead of grab_set(), but the grab_set() method is much better.
Another problem is that when option menu is open and I close the top level, the option menu is not destroyed and is displayed... of course, we can remove it manually with destroy() method.
thank you.

Example with this problem:
```python
from CTkScrollableDropdown import *
import customtkinter
import tkinter


class Top(customtkinter.CTkToplevel):
    def __init__(self):
        super().__init__()
        self.geometry("300x400")
        self.grab_set()
        # self.attributes("-topmost", True) # this method work
        data = ['test', 'test1', 'test2']
        option = customtkinter.CTkOptionMenu(
            self, width=225, anchor='center', button_hover_color='#2a2a2a', fg_color='#4b4c4d', button_color='#3a3b3b')
        option.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)
        option.set('test')
        option_frame = CTkScrollableDropdown(option, values=data, frame_corner_radius=10, hover_color='#565656',
                              frame_border_width=1, command=lambda e: option.set(e))
        # option_frame.attributes("-topmost", True)  # this method work


root = customtkinter.CTk()
root.geometry("600x400")

customtkinter.CTkButton(root, text="Open top-level",
                        command=Top).place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

root.mainloop()
```

**Comment by Akascape** [comment]
@HassanAnari Hi, I have fixed the issue. First update to the new version.
Now you have to add these 3 new lines if you use grab_set() method, 
```python
option_frame.bind("<<Opened>>", lambda _: self.grab_release())
option_frame.bind("<<Selected>>", lambda _: self.grab_set())
option_frame.bind("<<Closed>>", lambda _: self.grab_set())
```
>Another problem is that when option menu is open and I close the top level, the option menu is not destroyed and is displayed... of course, we can remove it manually with destroy() method.

I have also fixed this destroy issue. Thanks
